apiVersion: v1
kind: Secret
metadata:
  name: {{ include "game-bot.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "game-bot.labels" . | nindent 4 }}
type: Opaque
data:
  discord-webhook-url: {{ .Values.secrets.discordWebhookUrl | b64enc | quote }}